/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Cat_CONSTANTS_H
#define Cat_CONSTANTS_H

#include "Cat_types.h"



class CatConstants {
 public:
  CatConstants();

};

extern const CatConstants g_Cat_constants;



#endif
