/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Cat_constants.h"



const CatConstants g_Cat_constants;

CatConstants::CatConstants() {
}



